package com.jorgenavarro.validation.entities;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author Jorge Navarro
 * Basic class client
 */
@Valid
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name = "clients")
public class Client {

    /**
     * Client ID UNIQUE
     * Autogenerated
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name from the client UNIQUE
     * Min size 3
     * Not empty
     */
    @Size(min = 3, message = "The name must have at least 3 characters")
    @NotEmpty(message = "The name cannot be empty")
    private String userName;

    /**
     * Password from the client
     * Min size 8
     */
    @Size(min = 8, message = "The password must have at least 8 characters")
    private String password;


    /**
     * Age from the client
     * Min age 1
     * Max age 99
     */
    @Min(value = 1, message = "The age must be at least 1")
    @Max(value = 99, message = "The age must be at most 99")
    private int age;

    /**
     * Valid email from the client
     * Not empty
     */
    @Email(message = "The email must be valid")
    @NotEmpty(message = "The email cannot be empty")
    private String email;

    

}
